"""empty message

Revision ID: 3974d915e6e0
Revises: 
Create Date: 2023-10-31 17:01:37.987749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3974d915e6e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=40), nullable=False),
    sa.Column('lastName', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('repps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('displayName', sa.String(length=40), nullable=False),
    sa.Column('linkName', sa.String(length=40), nullable=False),
    sa.Column('tiktok', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('applemusic', sa.String(), nullable=True),
    sa.Column('spotify', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('external', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkName'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('repppages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reppId', sa.Integer(), nullable=False),
    sa.Column('mainImage', sa.String(), nullable=False),
    sa.Column('isBanner', sa.Boolean(), nullable=False),
    sa.Column('mainVideo', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('newsletter', sa.String(), nullable=True),
    sa.Column('businessInquiries', sa.String(), nullable=True),
    sa.Column('videos', sa.Boolean(), nullable=False),
    sa.Column('shop', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reppId'], ['repps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reppId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repppages')
    op.drop_table('repps')
    op.drop_table('users')
    # ### end Alembic commands ###